title: "[📚 공유] 제목을 입력하세요"
labels: []
body:
  - type: markdown
    attributes:
      value: |
        ### 🌟 자료 공유 가이드  
        - **공유할 내용**을 간략히 요약해주세요.  
        - 자료의 출처 및 관련 내용을 추가하면 좋아요!  
        - 링크를 추가할 경우 아래 형식을 참고해주세요. 
    validations:
      required: true
      
  - type: textarea
    id: content
    attributes:
      label: "📖 공유 내용"
      description: "이 자료가 어떤 내용인지 간략하게 설명해주세요."
      placeholder: "예시: 이 논문은 Transformer 모델의 구조와 발전 과정에 대해 다룹니다."
    validations:
      required: true

  - type: textarea
    id: links
    attributes:
      label: "🔗 관련 링크"
      description: "관련된 자료의 링크를 아래 형식으로 입력해주세요."
      placeholder: |
        - [자료 제목](링크)
        - [추가 자료](링크)
    validations:
      required: false